### ISSUE TITLE
No Source Code?

### ISSUE THREAD

**Issue by cubanismo** [Zloyduh/cws#1]
I'd like to compile a Linux and Mac version, but there's no source code available. Any chance you could share it? Would also be interested in comparing to the versions from here: https://github.com/JNJ3D

**Comment by Zloyduh** [comment]
I need to automate certain steps and rearrange the code.  This will take some time. Thanks.

**Comment by Zloyduh** [comment]
Here comes the code.

**Comment by cubanismo** [comment]
Thanks!
