### ISSUE TITLE
Improper image usage

### ISSUE THREAD

**Issue by Munckis** [Zloyduh/cws#2]
If CWS output is used in a monoprice mini the first 2 layers will use the preview images in the cws/zip file instead of starting at proper numerical files.  If preview files (preview.png and preview_cropping.png) are manually deleted, print will work as intended.

**Comment by Zloyduh** [comment]
That's nice to know.  Thank you!
I'll try it out.

**Comment by Zloyduh** [comment]
The plugin now removes generated "preview" files.  Thanks for the tip!
