### ISSUE TITLE
Hey, mind helping me out? 

### ISSUE THREAD

**Issue by Thesnipest** [Zloyduh/cws#4]
Hey Z,
For context, this is my first printer...

I was given this printer as a gift and after a few days of digging and confusion wound up here. I've managed to install your plugin and even realized it only works with up to version 1.7.0 of Chitubox as far as I can tell, however I am admittedly very lost as I'm trying to implement the g-code profiles you provided into the settings box. I managed to slice a CWS file but noticed it was small and when I tried to use it on the printer it was stuck on "waiting..." which I assume means the file was just missing these instructions. 

Aside from that, I've learned to find files on Thingiverse, manage the physical printer and bought materials. Any advice and hopefully a solution to the g-code profile step might just be enough to get me printing! I've made too many pigs...

Thanks!

Ps (I now realize I can use Chitubox 1.9. I still had to remove the parenthesis in the description manually, so the plugin download needs to be updated I think.)

**Comment by Zloyduh** [comment]
Hi there.
I updated the compiled plugin:  ZloyduhCws.CHplugin.  That should now work for the latest version of Chitubox.

The printer that I have is Monoprice MP Mini Deluxe.  That's the one and only and that's what I test with.

Let's put away the profiles for now and make sure these are the steps you're taking:
1.  Install the plugin (menu -> help -> plugins).
2.  Open an STL file in Chitubox.
3.  Hit the big blue Slice button on the right side.
4.  ONLY when the slicing is done, there will appear a grey Save button on the right side where Slice button used to be.  Click it.
5.  Save Slicer dialog opens up.  In the bottom, Save as type:  CWS Zloyduh(*.cws).  This will take a while.  
6.  You should have a .cws file now as a result of step 5.  Check if it's the right size.  Also, cws is really a zip.  If you rename your file to .zip, you would be able to open it with a zip software or even just windows itself should open it.  There should be a bunch of image files there together with 1.gcode, default.slicing, manifest.xml files.  Check if all of these are in place.
7.  Load up your cws file on the flash drive and transfer it to the printer.  See if the printer takes this file and actually prints it.

I would start with some small and simple object.  See if it works.  Let me know the outcome.


Cheers!

~Z

**Comment by Thesnipest** [comment]
Hey I never got your plugin working unfortunately, i learned i could just format the stl files i find with chitubox and save that new file with supports and other files as an stl itself, from there i slice in the mp web ui and get a gif file, which I can double check is sliced correctly by opening the windows photo app.
